### ISSUE TITLE
[question] please tell me how to generate electricity.npy

### ISSUE THREAD

**Issue by saeeeeru** [rajatsen91/deepglo#1]
Thanks for releasing your source code.

I have a question about how to generate dataset.
When we download electricity dataset from link in your paper, 
there is txt file(LD2011_2014.txt) with data every 15 minutes from 2011-01-01 to 2015-01-01.

So, I wonder how to convert this .txt file to .npy in your google drive.
Please tell me how to generate electricity.npy.

Best Regards.

**Comment by rajatsen91** [comment]
There is a functionality in the released code to directly download the .npy files for all datasets used in the paper. After you have cloned the repo:

The datasets can be downloaded by the following commands (from inside the repo): 

cd datasets

bash download-data.sh 

This will download the files into repo/datasets/.
