### ISSUE TITLE
[question] creating global covariates

### ISSUE THREAD

**Issue by jyh2986** [rajatsen91/deepglo#2]
Hi,  thanks for sharing your code.

I have a question about creating global covariates. 

In the prediction, global covariates are calculated using F*Tx(X) as stated in the paper.

https://github.com/rajatsen91/deepglo/blob/54e0644d764f1ead65d4203b72c8634e2f6ea25e/DeepGLO/DeepGLO.py#L619-L630

However, In training, global covariate seems to be generated by Tx using input sequence directly instead of using factorized F and X (i.e. F*X). Is there any reason for this?

https://github.com/rajatsen91/deepglo/blob/54e0644d764f1ead65d4203b72c8634e2f6ea25e/DeepGLO/DeepGLO.py#L510-520

Best Regards.

**Comment by rajatsen91** [comment]
Thanks for catching this bug. I uploaded the wrong version of the code to the external repository. The numbers reported should hopefully still be correct. I am re-running all the experiments now with the changed package. If there are any changes I will add the new numbers in the repository and then close this issue.
