### ISSUE TITLE
which predictions are the final predictions?

### ISSUE THREAD

**Issue by vamp-ire-tap** [rajatsen91/deepglo#7]
In the paper, the authors commented that the final global predictions can be made with FX(te) where X(te) is forecasted with the local model. Are these final global predictions also the DeepGLO predictions? That is the proposed model? 
The confusion is because in the code, there is Wape global and only wape, which is the DeepGLO wape?

**Comment by rajatsen91** [comment]
The final predictions are predictions from T_Y TC network which takes as covariate the global prediction. So wape is the metric on the final prediction.
